### ISSUE TITLE
No Battery Icon

### ISSUE THREAD

**Issue by hehuichao** [ske1996/Matebook-x-pro-2019-Hackintosh-newest#1]
No Battery Icon

**Comment by ske1996** [comment]
> No Battery Icon

okay,thank you

i dont have that device,so other guy tested for me.maybe he didnt see that,thank you for telling me it

can you show me a screenshot which is in setting/battery？

**Comment by hehuichao** [comment]
> > No Battery Icon
> 
> okay,thank you
> 
> i dont have that device,so other guy tested for me.maybe he didnt see that,thank you for telling me it
> 
> can you show me a screenshot which is in setting/battery？

give me your email address

**Comment by ske1996** [comment]
> > > No Battery Icon
> > 
> > 
> > okay,thank you
> > i dont have that device,so other guy tested for me.maybe he didnt see that,thank you for telling me it
> > can you show me a screenshot which is in setting/battery？
> 
> give me your email address

no,you can po it here

**Comment by hehuichao** [comment]
![微信图片_20210604154105](https://user-images.githubusercontent.com/3467179/120765073-6a34db00-c54b-11eb-99bc-7da8cc732d5e.jpg)
![微信图片_20210604154111](https://user-images.githubusercontent.com/3467179/120765096-6f922580-c54b-11eb-8194-1a5b06b99070.jpg)
